"""changes in db tables add enrollment_modules and completed modules added new relations

Revision ID: 4023b0b3fe8d
Revises: 3c5ea2819062
Create Date: 2025-06-02 12:04:43.883639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4023b0b3fe8d'
down_revision = '3c5ea2819062'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_modules',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('user_profile_id', 'module_id')
    )
    op.create_table('enrolled_modules',
    sa.Column('user_profile_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('user_profile_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrolled_modules')
    op.drop_table('completed_modules')
    # ### end Alembic commands ###
