"""Added table for relation_ship bettwen teacher and module

Revision ID: 48c2694c62c6
Revises: e2a6f7131e05
Create Date: 2025-06-03 10:19:40.514240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c2694c62c6'
down_revision = 'e2a6f7131e05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_teachers',
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user_profile.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_teachers')
    # ### end Alembic commands ###
