"""db updates, fixes

Revision ID: 4e89e743c30f
Revises: 3e9271855e0b
Create Date: 2025-05-25 22:38:49.437200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e89e743c30f'
down_revision = '3e9271855e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required_module_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('module_requirement_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'module', ['required_module_id'], ['id'])
        batch_op.drop_column('requirement_module_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_module_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('module_requirement_ibfk_2'), 'module', ['requirement_module_id'], ['id'])
        batch_op.drop_column('required_module_id')

    # ### end Alembic commands ###
