"""updates

Revision ID: 51210e0f2649
Revises: cc98d392dadb
Create Date: 2025-05-23 10:48:08.371381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51210e0f2649'
down_revision = 'cc98d392dadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
