"""Remove registration_request table

Revision ID: b7ec1a791bdf
Revises: fb08c618ad1d
Create Date: 2025-05-30 14:24:52.118923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b7ec1a791bdf'
down_revision = 'fb08c618ad1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_request',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('study_program_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('reason', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('student_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('admin_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('processed_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['user_profile.id'], name=op.f('registration_request_ibfk_1')),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], name=op.f('registration_request_ibfk_2')),
    sa.ForeignKeyConstraint(['student_id'], ['user_profile.id'], name=op.f('registration_request_ibfk_3')),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_program.id'], name=op.f('registration_request_ibfk_4')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
