"""Grupes lenteles atnaujinimas

Revision ID: fb08c618ad1d
Revises: 35a510909ecc
Create Date: 2025-05-29 20:52:06.808267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb08c618ad1d'
down_revision = '35a510909ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_capacity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('max_capacity')

    # ### end Alembic commands ###
